# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\MAD_JJW\rez\pythonProject2\test_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from sgtk.platform.qt import QtCore, QtGui


class Ui_Dialog(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 549)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 56, 12))
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 500, 631, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 90, 631, 341))
        self.listView.setObjectName("listView")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 631, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.browse_button = QtGui.QPushButton(self.widget)
        self.browse_button.setText("")
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_3.addWidget(self.browse_button)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(11, 51, 631, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_button = QtGui.QPushButton(self.widget1)
        self.check_button.setMaximumSize(QtCore.QSize(70, 40))
        self.check_button.setObjectName("check_button")
        self.horizontalLayout_4.addWidget(self.check_button)
        self.uncheck_button = QtGui.QPushButton(self.widget1)
        self.uncheck_button.setMaximumSize(QtCore.QSize(80, 40))
        self.uncheck_button.setObjectName("uncheck_button")
        self.horizontalLayout_4.addWidget(self.uncheck_button)
        spacerItem = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setEnabled(True)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.widget1)
        self.comboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 460, 634, 37))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.excel_open_button = QtGui.QPushButton(self.widget2)
        self.excel_open_button.setMinimumSize(QtCore.QSize(0, 28))
        self.excel_open_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.excel_open_button.setObjectName("excel_open_button")
        self.horizontalLayout_5.addWidget(self.excel_open_button)
        self.excel_save_button = QtGui.QPushButton(self.widget2)
        self.excel_save_button.setMinimumSize(QtCore.QSize(0, 28))
        self.excel_save_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.excel_save_button.setObjectName("excel_save_button")
        self.horizontalLayout_5.addWidget(self.excel_save_button)
        spacerItem1 = QtGui.QSpacerItem(480, 30, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Excel"))
        self.pushButton_7.setText(_translate("MainWindow", "Publish"))
        self.label.setText(_translate("MainWindow", "SCAN PATH :"))
        self.check_button.setText(_translate("MainWindow", "check_all"))
        self.uncheck_button.setText(_translate("MainWindow", "uncheck_all"))
        self.label_2.setText(_translate("MainWindow", "Colorspace"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ACES - ACES2065-1"))
        self.excel_open_button.setText(_translate("MainWindow", "Open"))
        self.excel_save_button.setText(_translate("MainWindow", "Save"))

#
# if __name__ == "__main__":
#     import sys
#     app = QtGui.QApplication(sys.argv)
#     MainWindow = QtGui.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
